
name: Python Lint

# events
on:
  push: # run when push on any branch
  pull_request:
    types: [ opened, reopened]

# jobs
jobs:
  lint:
    name: python lint action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        strict: "high"
