
# events
on:
  pull_request:
    types: [ opened, reopened]

# jobs
jobs:
  echo_job:
    name: echo job
    runs-on: ubuntu-latest
    steps:
      - name: first step in the echo job
        run: echo "Hello CI!"
